{% set name = "labgrid" %}
{% set version = "25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/labgrid-{{ version }}.tar.gz
  sha256: 880aea4822601f2b13b7a95ba5f3f2b7f8efca8bd55318f29aad6da99deadbaf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - labgrid-autoinstall = labgrid.autoinstall.main:main
    - labgrid-client = labgrid.remote.client:main
    - labgrid-exporter = labgrid.remote.exporter:main
    - labgrid-suggest = labgrid.resource.suggest:main
    - labgrid-coordinator = labgrid.remote.coordinator:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ansicolors >=1.1.8
    - attrs >=21.4.0
    - grpcio >=1.64.1,<2.0.0
    - grpcio-reflection >=1.64.1,<2.0.0
    - protobuf >=5.27.0
    - jinja2 >=3.0.2
    - pexpect >=4.8.0
    - pyserial-labgrid >=3.4.0.1
    - pytest >=7.0.0
    - pyudev >=0.22.0
    - pyusb >=1.2.1
    - pyyaml >=6.0.1
    - requests >=2.26.0
    - xmodem >=0.4.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - labgrid
  commands:
    - labgrid-autoinstall --help
    - labgrid-client --help
    - labgrid-exporter --help
    - labgrid-suggest --help
    - labgrid-coordinator --help

about:
  home: https://labgrid.readthedocs.io/
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'Labgrid is an embedded board control python library with a focus on 
  testing, development and general automation.'

extra:
  recipe-maintainers:
    - RajeshwariSubramaniam
